SelectorItemID: 46
InventoryName: Test
SelectorName: Blaah
Lore Message: 'Players online: !players'
# !players is the player count on the specific server
############
#  Made By #
# Matt -   #
#Smartloser#